language: android 
sudo: false
addons:
  apt:
    packages:
      - imagemagick
      - p7zip-full
android:
  update_sdk: true
  components:
  - platform-tools
  - tools
  - build-tools-27.0.3
  - android-27
  - extra-google-m2repository
  - extra-android-m2repository

cache:
  directories:
    - $HOME/.gradle
    - $HOME/.android
    - $ANDROID_HOME
    - android-ndk-r15b
    - .gradle
    - .idea
    - mobile/build
    - libcore/build
    - libcore/libs
    - libcore/obj
before_cache:
  - find . -name *.lock -print | xargs -I {} -P 4 rm -rf {}
  - find $HOME/.gradle -name *.lock -print | xargs -I {} -P 4 rm -rf {}
  - find $HOME/.android -name *.lock -print | xargs -I {} -P 4 rm -rf {}

env:
- QUALITY=50

before_install:
- yes | sdkmanager --update
- yes | sdkmanager --licenses

- if [[ ! -f "android-ndk-r15b/ndk-build" ]]; then
    curl --retry 5 --connect-timeout 30 --location --remote-header-name --remote-name https://dl.google.com/android/repository/android-ndk-r15b-linux-x86_64.zip;
    7z x -y android-ndk-r15b-linux-x86_64.zip > /dev/null;
  fi

- curl --retry 5 --connect-timeout 30 --location --remote-header-name --remote-name https://github.com/purerosefallen/ygopro/archive/master.zip
- 7z x -y ygopro-master.zip > /dev/null
- cp -rf ygopro-master/cards.cdb mobile/assets/data
- cp -rf ygopro-master/strings.conf mobile/assets/data/conf
- cp -rf ygopro-master/lflist.conf mobile/assets/data/conf

- curl --retry 5 --connect-timeout 30 --location --remote-header-name --remote-name https://github.com/HuangYuNan/ygopro222-images/archive/master.zip
- 7z x -y ygopro222-images-master.zip > /dev/null
- mv -f ygopro222-images-master pics

- git clone --depth=1 https://github.com/purerosefallen/ygopro-scripts script

- curl --retry 5 --connect-timeout 30 --location --remote-header-name --remote-name https://github.com/moecube/ygopro-starter-pack/archive/master.zip
- 7z x -y ygopro-starter-pack-master.zip > /dev/null
- cp -rf ygopro-starter-pack-master/* mobile/assets/data

- rm -rf pics/thumbnail pics/*.db
- cd pics && ls *.jpg | xargs -I {} -P 4 convert -size 177x254! -quality $QUALITY {} {} && cd ..

- 7z a -mx0 -xr!.git* mobile/assets/data/pics.zip pics > /dev/null
- 7z a -mx0 -xr!.git* mobile/assets/data/scripts.zip script > /dev/null

- chmod 777 ./gradlew

script:
- cd libcore && ./../android-ndk-r15b/ndk-build -j8 && cd ..
- ./gradlew :mobile:assembleMycardRelease

before_deploy:
- mv -f ./mobile/build/outputs/apk/cn/release/mobile-cn-release.apk ./NanahiraMobile-$TRAVIS_TAG.apk
- mv -f ./mobile/build/outputs/apk/cn/release/output.json ./output-$TRAVIS_TAG.json

deploy:
  provider: releases
  api-key: $NANAHIRA
  file: 
  - NanahiraMobile-$TRAVIS_TAG.apk
  - output-$TRAVIS_TAG.json
  skip_cleanup: true
  on:
    tags: true
